### ISSUE TITLE
Change the relative size of the inner circle

### ISSUE THREAD

**Issue by Ojas-Gulati** [yoannmoinet/nipplejs#70] opened 2018-03-24 11:41 UTC
feature-request : AFAIK, the inner circle is always 50% of the size of the outer circle.
Would it be possible to change the size of this circle? e.g. make it 20% of the size of the outer circle?

**Comment by yoannmoinet** [comment] 2018-03-26 13:25
duplicate of #53

**Closed by yoannmoinet** 2018-03-26 13:25 UTC
