### ISSUE TITLE
mouse coords offset

### ISSUE THREAD

**Issue by vrracing** [yoannmoinet/nipplejs#39] opened 2016-10-14 21:52 UTC
I have a nipple working in a div with class scPanner which is enclosed in a flexbox

```
.scPanner {
    position: absolute;
    width: 88px;
    height: 88px;
    background: yellow;
}
```

and create it the following code...

```
            scope.nipple = element[0].querySelector('.scPanner');

            var options = {
                zone: scope.nipple,
                mode: 'static',
                color: 'red',
                position: {
                    left: '50px',
                    top: '50px'
                },
                size: 44
            };

            var nipple = nipplejs.create(options);
```

When I click on the nipple, the inner circle shoots up to the top.  If I drag the mouse down so the mouse pointer is below the scPanner div about the height of scPanner (~88px) then the inner circle will center and if I continue moving the mouse down, the inner circle will drop below the nipple's vertical centerline.

Any idea what is confusing the nipple's mouse coordinate code?  Only tried it in Chrome53 on Win10.

**Comment by yoannmoinet** [comment] 2016-10-16 10:13
Hi, I've created a JSFiddle of your setup.
I can't really reproduce your issue I think.

Can you tell me a bit more about it please?

Here's the fiddle: https://jsfiddle.net/NeekGerd/ykotkzow/1/

**Comment by vrracing** [comment] 2016-10-17 22:57
Thanks for responding!  I think I may have discovered a clue.  If I open the page, then the mouse coordinates used by nipple are off as I described before.  If I resize the page, then the coordinates match up correctly and the nipple responds as expected.  

I've had a similar issue with canvas and I have a theory as to what may be the root cause.  When I create the nipple, it isn't displayed because this is a single page app (Angular1) and the nipple isn't part of the initial rendering.  I bet coordinates are being calculated when the nipple isn't displayed and some are undefined, zero or a percentage of zero.

The way I fix this with the canvas (which is inherently non-responsive) is to detect window resize events and $broadcast a resize event thru an Angular mechanism.  The directive wrapping the canvas element sees that event ($on) then sets the size (width & height) of the canvas element to match its parent and everything works beautifully.  When changing routes or modes, I just broadcast that resize event and even though the canvas element was created in an unrendered div, it adjusts and works great.

The nipple is clearly detecting the screen resize so if there is a call that I can make to trigger the coords recalcs that'd be super.  It doesnt look like I can resend the options.

Thanks!

**Comment by yoannmoinet** [comment] 2016-10-18 07:41
Can you reproduce it with the fiddle?
I don't see any offset in the fiddle.

Without an usable example of your setup, I can't help you.

**Comment by vrracing** [comment] 2016-10-18 13:48
My suspicions have been proven correct.  If the nipple is initialized in a display:none container, it's mouse coords are boofed when it is displayed.  I updated your fiddle to demonstrate it.

https://jsfiddle.net/ykotkzow/13/

Thanks!

**Comment by yoannmoinet** [comment] 2016-10-19 08:00
Ok, I'll see what I can do with this.
This might cause issues in some edge cases like yours.

Side question though, 
why not instantiating the joystick at the moment you're showing the container?

Basically moving the `nipplejs.create(options)` into the `showIt()` function. 
And destroying it each time you need to hide the container again.

I feel like this would be a more efficient way to deal with this case, 
you don't need an idle joystick if not showing it, just destroy it, or not create it at all.

What do you think?

**Comment by vrracing** [comment] 2016-10-19 14:24
With the popularity of AngularJS and SPAs, I'm not convinced this is an edge case.  As the user navigates the routes, Angular populates the DOM with the new page (hidden so no flashing) and then displays the newly updated DOM.  So unfortunately, there is no "showIt()" function, I just added that to your fiddle to demonstrate the root cause.

You've given me an idea though.  I'll see if I can put the nipplejs.create in a timeout so it gets pushed to the back of the queue and then executed after the DOM is visible.  Probably icky but it just might work!

Thanks!

**Comment by yoannmoinet** [comment] 2016-10-19 14:26
Yeah I understand.

I'll still try to find a solution.
It's just I don't have it yet. So for the time being, you're probably better with a temporary hack.

**Comment by vrracing** [comment] 2016-10-19 15:09
I got it to work!  Here is how I did it in case someone else needs a workaround.

```
            var nipple = false; // handle to the nipplejs widget

            // fired when the window resizes, when changing routes or 
            // when making layout changes
            scope.$on('qq::resize', function () {

                // create nipple if it's container div is there with height and width
                if (!nipple && scope.nipple.clientHeight && scope.nipple.clientWidth) {

                    var options = {
                        zone: scope.nipple,
                        mode: 'static',
                        color: 'red',
                        position: {
                            left: '50px',
                            top: '50px'
                        },
                        size: 44
                    };

                    nipple = nipplejs.create(options);
                }
            });
```

To your earlier point this allows me to delay creating the nipple until the container DOM element is truly ready.

Thanks for your help!

**Comment by thebelin** [comment] 2017-07-17 21:18
This solution was helpful to me also, in a situation where the static nipple was being instantiated inside a container with display: none; before being displayed. The nipple would behave as if it were placed in the top left corner of the screen. It was possible to make a workaround which delayed the nipple instantiation until the display call for the element.

**Comment by mfosse** [comment] 2018-07-02 17:56
I found that dispatching a resize event with:
window.dispatchEvent(new Event("resize"));
solves this issue for me, since waiting to instantiate the joysticks until it was visible was not preferable for me

**Comment by yoannmoinet** [comment] 2018-12-23 15:47
Many solutions have been given for this issue. 
I'm closing this.

**Closed by yoannmoinet** 2018-12-23 15:47 UTC
Labels: bug
