### ISSUE TITLE
es6 module support

### ISSUE THREAD

**Issue by kkimdev** [yoannmoinet/nipplejs#68] opened 2018-02-05 02:32 UTC
It would be great if we can use es6 module import to use nipplejs

**Comment by yoannmoinet** [comment] 2018-03-26 13:26
I'll be working on a rewrite of the lib in a not so far future (hopefully).

It is in great need of a refresh.

**Comment by elmarti** [comment] 2018-03-31 20:56
```
import Nipple from 'nipplejs';

```
works fine for me, deconstructability would be nice though ie 
```
import { Nipple } from 'nipplejs';
```

**Comment by yoannmoinet** [comment] 2018-03-31 21:22
Thank you @elmarti for testing this out.

When you say:
> deconstructability would be nice

Out of curiosity, how that would be nicer than what's already working?

**Comment by elmarti** [comment] 2018-03-31 21:55
It seems to be a common design pattern with ES6, and I've just gotten used to seeing it over the default export so I think I naturally suggested it. I believe the actual reason for doing it is to make refactoring/extending easier and explicitly only importing the code you need which can be utilized in optimisation.. I suppose it's fine the way it is and my suggestion is largely anecdotal!

**Comment by yoannmoinet** [comment] 2018-03-31 22:23
I see your point, what do you think about : 
```javascript 
import { create } from 'nipplejs';
// Or, to keep the semantic straight.
import { create as createManager } from 'nipplejs';

const manager = createManager(options);
```

That would work I suppose and it's looking good 😄

**Comment by elmarti** [comment] 2018-04-01 06:30
I can confirm that works and looks good to me!

**Comment by yoannmoinet** [comment] 2018-04-10 12:02
Closing this since it's been covered, and actually already working.

**Closed by yoannmoinet** 2018-04-10 12:02 UTC
Labels: enhancement, question

**Comment by kkimdev** [comment] 2018-04-20 14:11
@elmarti that's not es6 module style.  

@yoannmoinet I noticed that you created es6-upgrade branch https://github.com/yoannmoinet/nipplejs/tree/feat/es6-upgrade and worked on that.  Will it be merged to master?

**Comment by yoannmoinet** [comment] 2018-04-20 14:35
@kkimdev yes, I'm  working on something to use an up to date development stack.
Feel free to have a look :)

@ramachandrajr, @elmarti you can load modules with an URi.
It's just that NippleJS doesn't support it out of the box.

It was working for others because they were using a transpiler like babel or bundling their code with webpack.

Once I'm done with the small refacto, it will work out of the box.
No ETA yet.

**Comment by kkimdev** [comment] 2018-04-20 15:12
@yoannmoinet Thanks! :)

I think ideally umd should be able to produce es6 module export, though due to the lack of es6 module feature detection, it can't be the same file though.
