### ISSUE TITLE
[Feature Request] Add different joystick shapes.

### ISSUE THREAD

**Issue by nik012003** [yoannmoinet/nipplejs#66] opened 2017-12-29 11:59 UTC
I think it would be useful to add other shapes other than the circle, like for example square or custom rectangle.

**Comment by yoannmoinet** [comment] 2018-01-02 16:03
Thank you for this, 
I think it is a duplicate of #9 

Happy new year, cheers!

**Closed by yoannmoinet** 2018-01-02 16:03 UTC
